version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build --tag samisdat/conway .

      # deploy the image
      - run: docker push samisdat/conway