---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - typescript
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - "**/__tests__/"
  - "jest.config.js"
  - "jest-serialize-conway.js"
  - "webpack.config.js"
  - "webpack.prod.config.js"
